/* tslint:disable */
/* eslint-disable */
/**
 * Tea Manager
 * A tea manager to manage teas, YES!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AddSessionRequest
 */
export interface AddSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof AddSessionRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AddSessionRequest
     */
    'teaId': string;
    /**
     * 
     * @type {string}
     * @memberof AddSessionRequest
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof AddSessionRequest
     */
    'amount': number;
    /**
     * 
     * @type {number}
     * @memberof AddSessionRequest
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddSessionRequest
     */
    'vesselId': string;
}
/**
 * 
 * @export
 * @interface AddTeaRequest
 */
export interface AddTeaRequest {
    /**
     * 
     * @type {string}
     * @memberof AddTeaRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AddTeaRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AddTeaRequest
     */
    'type': AddTeaRequestTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AddTeaRequest
     */
    'amount': number;
    /**
     * 
     * @type {string}
     * @memberof AddTeaRequest
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddTeaRequest
     */
    'vendor'?: string;
    /**
     * 
     * @type {number}
     * @memberof AddTeaRequest
     */
    'year'?: number;
}

export const AddTeaRequestTypeEnum = {
    Green: 'Green',
    Black: 'Black',
    Oolong: 'Oolong',
    Sheng: 'Sheng',
    Shou: 'Shou',
    Yellow: 'Yellow',
    White: 'White',
    Heicha: 'Heicha'
} as const;

export type AddTeaRequestTypeEnum = typeof AddTeaRequestTypeEnum[keyof typeof AddTeaRequestTypeEnum];

/**
 * 
 * @export
 * @interface AddVesselRequest
 */
export interface AddVesselRequest {
    /**
     * 
     * @type {string}
     * @memberof AddVesselRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AddVesselRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof AddVesselRequest
     */
    'capacity': number;
}

/**
 * SessionApi - axios parameter creator
 * @export
 */
export const SessionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a new session.
         * @param {AddSessionRequest} addSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSession: async (addSessionRequest: AddSessionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addSessionRequest' is not null or undefined
            assertParamExists('addSession', 'addSessionRequest', addSessionRequest)
            const localVarPath = `/addSession`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addSessionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all sessions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllSessions: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/viewAllSessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionApi - functional programming interface
 * @export
 */
export const SessionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionApiAxiosParamCreator(configuration)
    return {
        /**
         * Add a new session.
         * @param {AddSessionRequest} addSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addSession(addSessionRequest: AddSessionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addSession(addSessionRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get all sessions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async viewAllSessions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AddSessionRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.viewAllSessions(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SessionApi - factory interface
 * @export
 */
export const SessionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionApiFp(configuration)
    return {
        /**
         * Add a new session.
         * @param {AddSessionRequest} addSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSession(addSessionRequest: AddSessionRequest, options?: any): AxiosPromise<string> {
            return localVarFp.addSession(addSessionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all sessions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllSessions(options?: any): AxiosPromise<Array<AddSessionRequest>> {
            return localVarFp.viewAllSessions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SessionApi - object-oriented interface
 * @export
 * @class SessionApi
 * @extends {BaseAPI}
 */
export class SessionApi extends BaseAPI {
    /**
     * Add a new session.
     * @param {AddSessionRequest} addSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApi
     */
    public addSession(addSessionRequest: AddSessionRequest, options?: AxiosRequestConfig) {
        return SessionApiFp(this.configuration).addSession(addSessionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all sessions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApi
     */
    public viewAllSessions(options?: AxiosRequestConfig) {
        return SessionApiFp(this.configuration).viewAllSessions(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * TeaApi - axios parameter creator
 * @export
 */
export const TeaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a new tea.
         * @param {AddTeaRequest} addTeaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTea: async (addTeaRequest: AddTeaRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addTeaRequest' is not null or undefined
            assertParamExists('addTea', 'addTeaRequest', addTeaRequest)
            const localVarPath = `/addTea`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTeaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all teas.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllTeas: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/viewAllTeas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeaApi - functional programming interface
 * @export
 */
export const TeaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeaApiAxiosParamCreator(configuration)
    return {
        /**
         * Add a new tea.
         * @param {AddTeaRequest} addTeaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTea(addTeaRequest: AddTeaRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTea(addTeaRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get all teas.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async viewAllTeas(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AddTeaRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.viewAllTeas(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TeaApi - factory interface
 * @export
 */
export const TeaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeaApiFp(configuration)
    return {
        /**
         * Add a new tea.
         * @param {AddTeaRequest} addTeaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTea(addTeaRequest: AddTeaRequest, options?: any): AxiosPromise<string> {
            return localVarFp.addTea(addTeaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all teas.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllTeas(options?: any): AxiosPromise<Array<AddTeaRequest>> {
            return localVarFp.viewAllTeas(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeaApi - object-oriented interface
 * @export
 * @class TeaApi
 * @extends {BaseAPI}
 */
export class TeaApi extends BaseAPI {
    /**
     * Add a new tea.
     * @param {AddTeaRequest} addTeaRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeaApi
     */
    public addTea(addTeaRequest: AddTeaRequest, options?: AxiosRequestConfig) {
        return TeaApiFp(this.configuration).addTea(addTeaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all teas.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeaApi
     */
    public viewAllTeas(options?: AxiosRequestConfig) {
        return TeaApiFp(this.configuration).viewAllTeas(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * VesselApi - axios parameter creator
 * @export
 */
export const VesselApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a new vessel.
         * @param {AddVesselRequest} addVesselRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVessel: async (addVesselRequest: AddVesselRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addVesselRequest' is not null or undefined
            assertParamExists('addVessel', 'addVesselRequest', addVesselRequest)
            const localVarPath = `/addVessel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addVesselRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all vessels.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllVessels: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/viewAllVessels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VesselApi - functional programming interface
 * @export
 */
export const VesselApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VesselApiAxiosParamCreator(configuration)
    return {
        /**
         * Add a new vessel.
         * @param {AddVesselRequest} addVesselRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addVessel(addVesselRequest: AddVesselRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addVessel(addVesselRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get all vessels.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async viewAllVessels(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AddVesselRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.viewAllVessels(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * VesselApi - factory interface
 * @export
 */
export const VesselApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VesselApiFp(configuration)
    return {
        /**
         * Add a new vessel.
         * @param {AddVesselRequest} addVesselRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVessel(addVesselRequest: AddVesselRequest, options?: any): AxiosPromise<string> {
            return localVarFp.addVessel(addVesselRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all vessels.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAllVessels(options?: any): AxiosPromise<Array<AddVesselRequest>> {
            return localVarFp.viewAllVessels(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VesselApi - object-oriented interface
 * @export
 * @class VesselApi
 * @extends {BaseAPI}
 */
export class VesselApi extends BaseAPI {
    /**
     * Add a new vessel.
     * @param {AddVesselRequest} addVesselRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselApi
     */
    public addVessel(addVesselRequest: AddVesselRequest, options?: AxiosRequestConfig) {
        return VesselApiFp(this.configuration).addVessel(addVesselRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all vessels.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VesselApi
     */
    public viewAllVessels(options?: AxiosRequestConfig) {
        return VesselApiFp(this.configuration).viewAllVessels(options).then((request) => request(this.axios, this.basePath));
    }
}


